export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const POST_POSTS_REQUEST = 'POST_POSTS_REQUEST';
export const POST_POSTS_SUCCESS = 'POST_POSTS_SUCCESS';
export const POST_POSTS_FAILURE = 'POST_POSTS_FAILURE';

export const HANDLE_MODAL_SHOW = 'HANDLE_MODAL_SHOW';
export const HANDLE_MODAL_CANCEL = 'HANDLE_MODAL_CANCEL';
