/*
 *
 * Board constants
 *
 */

export const DEFAULT_ACTION = 'app/Board/DEFAULT_ACTION';
export const POST_GET_ALL_REQUEST = 'POST_GET_ALL_REQUEST';
export const POST_GET_ALL_SUCCESS = 'POST_GET_ALL_SUCCESS';
export const POST_GET_ALL_FAILURE = 'POST_GET_ALL_FAILURE';
export const POST_GET_BY_ID_REQUEST = 'POST_GET_BY_ID_REQUEST';
export const POST_GET_BY_ID_SUCCESS = 'POST_GET_BY_ID_SUCCESS';
export const POST_GET_BY_ID_FAILURE = 'POST_GET_BY_ID_FAILURE';
