export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const POST_POSTS_REQUEST = 'POST_POSTS_REQUEST';
export const POST_POSTS_SUCCESS = 'POST_POSTS_SUCCESS';
export const POST_POSTS_FAILURE = 'POST_POSTS_FAILURE';

export const HANDLE_MODAL_SHOW = 'HANDLE_MODAL_SHOW';
export const HANDLE_MODAL_CANCEL = 'HANDLE_MODAL_CANCEL';

export const ON_CHANGE_TITLE = 'ON_CHANGE_TITLE';
export const ON_CHANGE_TEXT = 'ON_CHANGE_TEXT';
export const ON_CHANGE_ADD_PHOTO = 'ON_CHANGE_ADD_PHOTO';
export const ON_CHANGE_DEL_PHOTO = 'ON_CHANGE_DEL_PHOTO';
