export const POST_SIGN_IN_REQUEST = 'POST_SIGN_IN_REQUEST';
export const POST_SIGN_IN_SUCCESS = 'POST_SIGN_IN_SUCCESS';
export const POST_SIGN_IN_FAILURE = 'POST_SIGN_IN_FAILURE';

export const ON_CHANGE_EMAIL = 'ON_CHANGE_EMAIL';
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD';
